// This file will be auto-generated by: supabase gen types typescript --linked > types/database.ts
// For now, define the core types manually

export type MembershipTier = 'member' | 'silver' | 'gold' | 'platinum' | 'laureate';
export type MemberStatus = 'pending' | 'active' | 'suspended' | 'inactive';
export type EventType = 'gala' | 'networking' | 'dinner' | 'lifestyle' | 'collaboration';
export type RsvpStatus = 'confirmed' | 'waitlisted' | 'cancelled';
export type OpportunityType = 'co_invest' | 'board' | 'speaking' | 'procurement' | 'advisory';
export type AlignedStage = 'new' | 'accepted' | 'revealed' | 'expired' | 'declined';
export type NotificationType = 'pulse' | 'aligned' | 'event' | 'tier_change' | 'system';
export type OnboardingTimeFocus =
  | 'building'
  | 'investing'
  | 'operating'
  | 'creating'
  | 'performing'
  | 'specialising';
export type OnboardingWorkStage =
  | 'idea'
  | 'building'
  | 'launched'
  | 'traction'
  | 'scaling'
  | 'established';
export type OnboardingCommunityNeed =
  | 'capital'
  | 'talent'
  | 'customers'
  | 'collaborators'
  | 'distribution'
  | 'counsel'
  | 'community';
export type OnboardingAxis =
  | 'investor'
  | 'founder'
  | 'operator'
  | 'creator'
  | 'domain_specialist'
  | 'artist';

export interface Member {
  id: string;
  display_id: string;
  tier: MembershipTier;
  status: MemberStatus;
  full_name: string;
  email: string;
  photo_url: string | null;
  bio: string | null;
  industry: string | null;
  city: string | null;
  company: string | null;
  skills: string[];
  interests: string[];
  current_project: string | null;
  title: string | null;
  consent_given_at: string | null;
  consent_version: string | null;
  expo_push_token: string | null;
  notification_preferences: {
    pulse: boolean;
    aligned: boolean;
    events: boolean;
  };
  onboarded_at: string | null;
  invited_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface Event {
  id: number;
  type: EventType;
  title: string;
  description: string | null;
  min_tier: MembershipTier;
  capacity: number | null;
  starts_at: string;
  ends_at: string | null;
  early_access_at: string | null;
  general_access_at: string | null;
  venue_name: string | null;
  venue_address: string | null;
  venue_lat: number | null;
  venue_lng: number | null;
  eventbrite_id: string | null;
  cover_image_path: string | null;
  dress_code: string | null;
  registration_url: string | null;
  is_featured: boolean | null;
  created_at: string;
  updated_at: string;
}

export interface EventRsvp {
  id: number;
  event_id: number;
  member_id: string;
  status: RsvpStatus;
  checked_in_at: string | null;
  checked_in_by: string | null;
  created_at: string;
}

export interface PulseEdition {
  id: number;
  publish_date: string;
  status: string;
  headline: string;
  summary_content: any;
  full_content: any;
  stats: Record<string, number>;
  hero_image_path: string | null;
  created_at: string;
  updated_at: string;
}

export interface CorridorOpportunity {
  id: number;
  type: OpportunityType;
  title: string;
  description: string | null;
  min_tier: MembershipTier;
  closing_date: string | null;
  posted_by: string | null;
  partner_name: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface AlignedMatch {
  id: number;
  member_a: string;
  member_b: string;
  stage: AlignedStage;
  a_decision: string | null;
  b_decision: string | null;
  match_reasons: any[];
  match_score: number | null;
  expires_at: string;
  week_of: string;
  created_at: string;
}

export interface Notification {
  id: number;
  member_id: string;
  type: NotificationType;
  title: string;
  body: string | null;
  data: any;
  read_at: string | null;
  created_at: string;
}

export interface MemberOnboardingResponse {
  member_id: string;
  investor_score: number;
  founder_score: number;
  operator_score: number;
  creator_score: number;
  domain_specialist_score: number;
  artist_score: number;
  time_focus: OnboardingTimeFocus;
  current_stage: OnboardingWorkStage;
  community_need: OnboardingCommunityNeed;
  consent_version: string;
  completed_at: string;
  updated_at: string;
}

export interface MemberOnboardingSnapshot {
  member_id: string;
  primary_axis: OnboardingAxis;
  secondary_axis: OnboardingAxis | null;
  confidence: number;
  scores: Record<OnboardingAxis, number>;
  updated_at: string;
}

export interface CorridorInterest {
  id: number;
  member_id: string;
  opportunity_id: number;
  status: 'pending' | 'reviewed' | 'accepted' | 'declined';
  message: string | null;
  expressed_at: string;
  reviewed_at: string | null;
}

export interface AlignedTile {
  id: string;
  user_id: string;
  type: 'project' | 'interest';
  description: string;
  image_url: string | null;
  image_path: string | null;
  tags: string[];
  location: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Connection {
  id: string;
  user_a: string;
  user_b: string;
  matched_via: 'project' | 'interest' | 'pass';
  tile_a_id: string | null;
  tile_b_id: string | null;
  status: 'mutual' | 'archived';
  connected_at: string;
}

// ─── Intelligence Feed Types ───────────────────────────────

export type NewsRegion = 'australia' | 'uk' | 'africa' | 'americas' | 'global';

export type ContentMediaType = 'article' | 'editorial' | 'video' | 'audio' | 'digest';

export type TrackedEntityKind = 'person' | 'company' | 'theme';

export interface FollowableEntity {
  id: number;
  kind: TrackedEntityKind;
  name: string;
  industry: string | null;
  region: NewsRegion | null;
}

export interface NewsFeedItem {
  id: number;
  source_name: string;
  source_region: NewsRegion;
  url: string;
  title: string;
  snippet: string | null;
  image_url: string | null;
  published_at: string;
  topics: string[];
  regions: string[];
  entities: string[];
  summary: string | null;
  media_type: ContentMediaType;
  duration_seconds: number | null;
  format_meta: Record<string, unknown>;
  is_saved: boolean;
  matched_entity: string | null;
  score: number;
}

export interface SavedArticleItem {
  id: number;
  source_name: string;
  url: string;
  title: string;
  snippet: string | null;
  image_url: string | null;
  published_at: string;
  saved_at: string;
}

export interface FeedInterest {
  tag: string;
  weight: number;
  declared: boolean;
}

export type NewsEventType = 'impression' | 'open' | 'dwell' | 'save' | 'unsave' | 'hide';

// ─── Map Feature Types ─────────────────────────────────────

export type ProjectCategory = 'venture' | 'advisory' | 'creative' | 'impact' | 'culture' | 'health' | 'tech';
export type ProjectStatus = 'pending' | 'approved' | 'rejected';
export type GeoLevel = 'country' | 'state' | 'city';

export interface RegionCentroid {
  id: string;
  country_code: string;
  country_name: string;
  state_province: string | null;
  city_name: string | null;
  population: number | null;
  display_label: string;
  geo_level: GeoLevel;
}

export interface Project {
  id: string;
  creator_id: string;
  name: string;
  description: string;
  category: ProjectCategory;
  region_id: string;
  image_url: string | null;
  image_path: string | null;
  external_link: string | null;
  status: ProjectStatus;
  rejection_reason: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  // Joined fields
  region?: RegionCentroid;
  creator?: Pick<Member, 'id' | 'full_name' | 'photo_url'>;
}

export interface ProjectBookmark {
  id: string;
  member_id: string;
  project_id: string;
  created_at: string;
}

// Map cache types (returned from RPCs)
export interface MapCountryCluster {
  country_code: string;
  country_name: string;
  project_count: number;
  categories: Record<ProjectCategory, number>;
  lat: number;
  lng: number;
}

export interface MapStateCluster {
  state_province: string;
  display_label: string;
  project_count: number;
  categories: Record<ProjectCategory, number>;
  lat: number;
  lng: number;
}

export interface MapProject {
  project_id: string;
  name: string;
  description: string;
  category: ProjectCategory;
  creator_first_name: string;
  display_label: string;
  image_url: string | null;
  external_link: string | null;
  lat: number;
  lng: number;
}
