// This file will be auto-generated by: supabase gen types typescript --linked > types/database.ts
// For now, define the core types manually

export type MembershipTier = 'member' | 'silver' | 'platinum' | 'laureate';
export type MemberStatus = 'pending' | 'active' | 'suspended' | 'inactive';
export type EventType = 'vibes' | 'dinner' | 'talk' | 'gala';
export type RsvpStatus = 'confirmed' | 'waitlisted' | 'cancelled';
export type OpportunityType = 'co_invest' | 'board' | 'speaking' | 'procurement' | 'advisory';
export type AlignedStage = 'new' | 'accepted' | 'revealed' | 'expired' | 'declined';
export type NotificationType = 'pulse' | 'aligned' | 'event' | 'tier_change' | 'system';

export interface Member {
  id: string;
  display_id: string;
  tier: MembershipTier;
  status: MemberStatus;
  full_name: string;
  email: string;
  photo_url: string | null;
  bio: string | null;
  industry: string | null;
  city: string | null;
  company: string | null;
  title: string | null;
  consent_given_at: string | null;
  consent_version: string | null;
  expo_push_token: string | null;
  notification_preferences: {
    pulse: boolean;
    aligned: boolean;
    events: boolean;
  };
  onboarded_at: string | null;
  invited_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface Event {
  id: number;
  type: EventType;
  title: string;
  description: string | null;
  min_tier: MembershipTier;
  capacity: number | null;
  starts_at: string;
  ends_at: string | null;
  early_access_at: string | null;
  general_access_at: string | null;
  venue_name: string | null;
  venue_address: string | null;
  venue_lat: number | null;
  venue_lng: number | null;
  eventbrite_id: string | null;
  cover_image_path: string | null;
  created_at: string;
  updated_at: string;
}

export interface EventRsvp {
  id: number;
  event_id: number;
  member_id: string;
  status: RsvpStatus;
  checked_in_at: string | null;
  checked_in_by: string | null;
  created_at: string;
}

export interface PulseEdition {
  id: number;
  publish_date: string;
  status: string;
  headline: string;
  summary_content: any;
  full_content: any;
  stats: Record<string, number>;
  hero_image_path: string | null;
  created_at: string;
  updated_at: string;
}

export interface CorridorOpportunity {
  id: number;
  type: OpportunityType;
  title: string;
  description: string | null;
  min_tier: MembershipTier;
  closing_date: string | null;
  posted_by: string | null;
  partner_name: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface AlignedMatch {
  id: number;
  member_a: string;
  member_b: string;
  stage: AlignedStage;
  a_decision: string | null;
  b_decision: string | null;
  match_reasons: any[];
  match_score: number | null;
  expires_at: string;
  week_of: string;
  created_at: string;
}

export interface Notification {
  id: number;
  member_id: string;
  type: NotificationType;
  title: string;
  body: string | null;
  data: any;
  read_at: string | null;
  created_at: string;
}
